### ISSUE TITLE
Inability to Delete Previously Added Companies

### ISSUE THREAD

**Issue by TheTharz** [Life-Pill/pharmacy-pos-main-backend#106]
**Issue: Inability to Delete Previously Added Companies**

**Description:**
Users are encountering difficulties when attempting to delete companies that were added to the system before. Deleting these pre-existing entries results in a server error (status code: 500), preventing successful deletion.

**Endpoint:**
- DELETE `/lifepill/v1/supplierCompanies/delete-supplier-company/{id}`

**Steps to Reproduce:**
1. Select a company that was added to the system before.
2. Make a DELETE request to the above-mentioned endpoint with the ID of the selected company.
3. Encounter a server error (status code: 500) preventing successful deletion.

**Expected Behavior:**
Users should be able to delete previously added companies without encountering server errors.

**Additional Information:**
- The issue seems to be specific to companies that were added to the system before.
- New companies added to the system can be deleted without any issues.
- The server error message returned is: "An error occurred while processing your request. Please try again later."

**Resolution:**
Further investigation is necessary to identify the root cause of this issue. It could be related to how the backend handles deletion requests for pre-existing companies or potential inconsistencies in the database. Debugging and testing are required to address and resolve this issue effectively.

**Comment by PramithaMJ** [comment]
**Issue:** Inability to Delete Previously Added Companies

**Description:**
Users were encountering difficulties when attempting to delete companies that were added to the system before. Deleting these pre-existing entries resulted in a server error (status code: 500), preventing successful deletion.

**Endpoint:**

```
DELETE /lifepill/v1/supplierCompanies/delete-supplier-company/{id}
```

**Steps to Reproduce:**
1. Select a company that was added to the system before.
2. Make a DELETE request to the above-mentioned endpoint with the ID of the selected company.
3. Encounter a server error (status code: 500) preventing successful deletion.

**Expected Behavior:**
Users should be able to delete previously added companies without encountering server errors.

**Additional Information:**
- The issue seemed specific to companies that were added to the system before.
- New companies added to the system could be deleted without any issues.
- The server error message returned was: "An error occurred while processing your request. Please try again later."

**Resolution:**
Further investigation was necessary to identify the root cause of this issue, which could have been related to how the backend handled deletion requests for pre-existing companies or potential inconsistencies in the database. Debugging and testing were required to address and resolve this issue effectively.

**Status:** Resolved

Best regards,  
Pramitha Jayasooriya  
Backend Developer at LifePill  
[https://pramithamj.me](https://pramithamj.me)

---
