### ISSUE TITLE
Return Array of Order Interface When Branch ID is Passed

### ISSUE THREAD

**Issue by TheTharz** [Life-Pill/pharmacy-pos-main-backend#115]
# Issue: Return Array of Order Interface When Branch ID is Passed

## Description
When a branch ID is passed to the endpoint, the response should include an array of objects conforming to the defined interface structures. Currently, the endpoint might not provide the expected structure of data when queried with a branch ID.

## Expected Behavior
- When querying the endpoint with a branch ID, the response should include an array of objects adhering to the structure defined by the `Order` interface.
- Each object in the array should contain properties as specified in the `Order` interface, including `employerId`, `branchId`, `orderDate`, `total`, and `groupedOrderDetails`.
- The `groupedOrderDetails` property should contain an object conforming to the `GroupedOrderDetails` interface, which consists of `orderDetails`, `paymentDetails`, and `orderCount`.

## Steps to Reproduce
1. Make a GET request to the endpoint with a branch ID.
2. Inspect the response structure to ensure it conforms to the expected structure described above.

## Example
```
GET /endpoint?branchId=123
Response:
[
  {
    "employerId": 1,
    "branchId": 123,
    "orderDate": "2024-06-08",
    "total": 500,
    "groupedOrderDetails": {
      "orderDetails": [
        {
          "name": "Product A",
          "amount": 2,
          "id": 101
        },
        {
          "name": "Product B",
          "amount": 3,
          "id": 102
        }
      ],
      "paymentDetails": {
        "paymentMethod": "Credit Card",
        "paymentAmount": 500,
        "paymentDate": "2024-06-08",
        "paymentNotes": "Payment for order",
        "paymentDiscount": 0,
        "payedAmount": 500
      },
      "orderCount": 2
    }
  }
]
```

**Comment by PramithaMJ** [comment]
**Issue:** Return Array of Order Interface When Branch ID is Passed

**Description:**
When a branch ID is passed to the endpoint, the response should include an array of objects conforming to the defined interface structures. Currently, the endpoint might not provide the expected structure of data when queried with a branch ID.

**Expected Behavior:**
- When querying the endpoint with a branch ID, the response should include an array of objects adhering to the structure defined by the Order interface.
- Each object in the array should contain properties as specified in the Order interface, including `employerId`, `branchId`, `orderDate`, `total`, and `groupedOrderDetails`.
- The `groupedOrderDetails` property should contain an object conforming to the GroupedOrderDetails interface, which consists of `orderDetails`, `paymentDetails`, and `orderCount`.

**Steps to Reproduce:**
1. Make a GET request to the endpoint with a branch ID.
2. Inspect the response structure to ensure it conforms to the expected structure described above.

**Example:**
```
GET /endpoint?branchId=123

Response:
[
  {
    "employerId": 1,
    "branchId": 123,
    "orderDate": "2024-06-08",
    "total": 500,
    "groupedOrderDetails": {
      "orderDetails": [
        {
          "name": "Product A",
          "amount": 2,
          "id": 101
        },
        {
          "name": "Product B",
          "amount": 3,
          "id": 102
        }
      ],
      "paymentDetails": {
        "paymentMethod": "Credit Card",
        "paymentAmount": 500,
        "paymentDate": "2024-06-08",
        "paymentNotes": "Payment for order",
        "paymentDiscount": 0,
        "payedAmount": 500
      },
      "orderCount": 2
    }
  }
]
```

---
Best regards,  
Pramitha Jayasooriya,
Backend Developer at LifePill,
https://pramithamj.me
